"""Item display names and tags for Foxhole game items."""

# Item display names - maps internal codes to human-readable names
ITEM_DISPLAY_NAMES: dict[str, str] = {
    "ATAmmo": "68mm",
    "ATGrenadeW": "BF5 White Ash Flask Grenade",
    "ATLargeAmmo": "94.5mm",
    "ATLaunchedGrenadeW": "B2 Varsi Anti-Tank Grenade",
    "ATRPGAmmo": "AP/RPG",
    "ATRPGC": "Venom c.II 35",
    "ATRPGHeavyC": "Bane 45",
    "ATRPGHeavyW": "Carnyx Anti-Tank Rocket Launcher",
    "ATRPGIndirectAmmo": "ARC/RPG",
    "ATRPGLightC": "Ignifist 30",
    "ATRPGTW": "Mounted Bonesaw MK.3",
    "ATRPGW": "Bonesaw MK.3",
    "ATRifleAmmo": "20mm",
    "ATRifleAssaultW": "228 Satterley Heavy Storm Rifle",
    "ATRifleAutomaticW": "Booker Greyhound Model 910",
    "ATRifleLightC": "Dawn Ve.II",
    "ATRifleSniperC": "Quickhatch Rt.I",
    "ATRifleTC": "Typhon ra.XII",
    "ATRifleW": "20 Neville Anti-Tank Rifle",
    "Aluminum": "Aluminum",
    "AluminumA": "Aluminum Alloy",
    "AmbulanceC": "R-12 Salus Ambulance",
    "AmbulanceFlameC": "R-12b Salva Flame Truck",
    "AmbulanceFlameW": "Dunne Dousing Engine 3r",
    "AmbulanceW": "Dunne Responder 3e",
    "AmmoUniformW": "Specialist's Overcoat",
    "ArmoredCar2LargeW": "O'Brien V.101 Freeman",
    "ArmoredCar2MultiW": "O'Brien v.200 Squire",
    "ArmoredCar2TwinW": "O'Brien V.190 Knave",
    "ArmoredCarATW": "O'Brien V.113 Gravekeeper",
    "ArmoredCarC": "T3 Xiphos",
    "ArmoredCarFlameW": "O'Brien V.130 Wild Jack",
    "ArmoredCarMobilityW": "O'Brien V.121 Highlander",
    "ArmoredCarOffensiveC": "T5 Percutio",
    "ArmoredCarTwinC": "T8 Gemini",
    "ArmoredCarW": "O'Brien V.110",
    "ArmourUniformC": "Velian Flak Vest",
    "ArmourUniformW": "Gunner's Breastplate",
    "AssaultRifleAmmo": "7.92mm",
    "AssaultRifleC": "Catara mo.II",
    "AssaultRifleHeavyC": "Dusk ce.III",
    "AssaultRifleHeavyW": "Booker Storm Rifle Model 838",
    "AssaultRifleW": "Aalto Storm Rifle 24",
    "Bandages": "Bandages",
    "BarbedWireMaterials": "Barbed Wire",
    "Barge": "BMS - Aquatipper",
    "BattleTankATC": "Lance-25 Hasta",
    "BattleTankAmmo": "75mm",
    "BattleTankC": "Lance-36",
    "BattleTankDefensiveW": "Flood Juggernaut Mk. VII",
    "BattleTankHeavyArtilleryC": "Lance-46 Sarissa",
    "BattleTankHeavyArtilleryW": "Flood Mk. IX Stain",
    "BattleTankW": "Flood Mk. I",
    "Bayonet": "Buckhorn CCQ-18",
    "Bicycle": "Blumfield LK205",
    "Binoculars": "Binoculars",
    "BloodPlasma": "Blood Plasma",
    "BusC": "R-15 Chariot",
    "BusW": "Dunne Caravaner 2f",
    "Cloth": "Basic Materials",
    "Coal": "Coal",
    "Components": "Components",
    "Concrete": "Concrete Materials",
    "ConcreteMixer": "Concrete Mixer",
    "Construction": "BMS - Universal Assembly Rig",
    "ConstructionEquipment": "Construction Equipment",
    "ConstructionUtility": "BMS - Fabricator",
    "Copper": "Copper",
    "CopperA": "Copper Alloy",
    "Crane": "BMS - Class 2 Mobile Auto-Crane",
    "CriticalSoldier": "Critically Wounded Soldier",
    "DemolitionRocketAmmo": "Shatter Missile",
    "DepthChargeAmmo": "Model-7 Evie",
    "DestroyerTankFlameW": "Noble Firebrand Mk. XVII",
    "DestroyerTankW": "Noble Widow MK. XIV",
    "Diesel": "Diesel",
    "EmplacedATW": "Leary Shellbore 68mm",
    "EmplacedHeavyArtilleryC": "50-500 Thunderbolt Cannon",
    "EmplacedHeavyArtilleryW": "Huber Exalt 150mm",
    "EmplacedIndirectC": "DAE 1o-3 Polybolos",
    "EmplacedInfantryC": "DAE 1b-2 Serra",
    "EmplacedInfantryW": "Leary Snare Trap 127",
    "EmplacedLightArtilleryW": "Huber Lariat 120mm",
    "EngineerUniformC": "Fabri Rucksack",
    "EngineerUniformW": "Sapper Gear",
    "Explosive": "Explosive Powder",
    "ExplosiveLightC": "Hydra's Whisper",
    "ExplosiveTripod": "Havoc Charge",
    "FacilityCoal1": "Coke",
    "FacilityComponents1": "Damaged Components",
    "FacilityMaterials1": "Construction Materials",
    "FacilityMaterials10": "Unstable Substances",
    "FacilityMaterials11": "Thermal Shielding",
    "FacilityMaterials2": "Processed Construction Materials",
    "FacilityMaterials3": "Steel Construction Materials",
    "FacilityMaterials4": "Assembly Materials I",
    "FacilityMaterials5": "Assembly Materials II",
    "FacilityMaterials6": "Assembly Materials III",
    "FacilityMaterials7": "Assembly Materials IV",
    "FacilityMaterials8": "Assembly Materials V",
    "FacilityMaterials9": "Rare Alloys",
    "FacilityOil1": "Heavy Oil",
    "FacilityOil2": "Enriched Oil",
    "FieldAT2C": "GA6 Cestus",
    "FieldAT2W": "Duncan's Coin 20mm",
    "FieldATC": "AA-2 Battering Ram",
    "FieldATDamageW": "Balfour Rampart 68mm",
    "FieldATW": "Collins Cannon 68mm",
    "FieldCannonDamageC": "40-45 Smelter",
    "FieldCannonW": "Balfour Wolfhound 40mm",
    "FieldMGC": "G40 Sagittarii",
    "FieldMGW": "Swallowtail 988/127-2",
    "FieldMortarC": "30-250 Tisiphone Field Cannon",
    "FieldMortarW": "Balfour Falconer 250mm",
    "FireRocketAmmo": "4C-Fire Rocket",
    "FirstAidKit": "First Aid Kit",
    "FlameAmmo": "Flame Ammo",
    "FlameBackpackC": "Molten Wind v.II Ammo",
    "FlameBackpackW": "Willow's Bane Ammo",
    "FlameTorchC": "Molten Wind v.II Flame Torch",
    "FlameTorchW": "Willow's Bane Model 845",
    "FlatbedTruck": "BMS - Packmule Flatbed",
    "Freighter": "BMS - Ironship",
    "GasMask": "Gas Mask",
    "GasMaskFilter": "Gas Mask Filter",
    "GreenAsh": "Green Ash Grenade",
    "GrenadeAdapter": "The Ospreay",
    "GrenadeC": "Bomastone Grenade",
    "GrenadeLauncherC": "KLG901-2 Lunaire F",
    "GrenadeLauncherTC": "Mounted Fissura gd.I",
    "GrenadeUniformC": "Grenadier's Baldric",
    "GrenadeW": "A3 Harpa Fragmentation Grenade",
    "GroundMaterials": "Gravel",
    "GunboatC": "Type C Charon",
    "GunboatW": "74b-1 Ronan Gunship",
    "HEGrenade": "Mammon 91-b",
    "HELaunchedGrenade": "Tremola Grenade GPb-1",
    "HERocketAmmo": "3C-High Explosive Rocket",
    "HalfTrackArtilleryC": "HH-d Peltast",
    "HalfTrackC": "HH-a Javelin",
    "HalfTrackDefensiveC": "HH-b Hoplite",
    "HalfTrackOffensiveW": "Niska Mk. II Blinder",
    "HalfTrackTwinW": "Niska Mk. III Scar Twin",
    "HalfTrackW": "Niska Mk. I Gun Motor Carriage",
    "HalftrackMultiW": "Niska-Rycker Mk. IX Skycaller",
    "Harvester": "BMS - Scrap Hauler",
    "HeavyArtilleryAmmo": "150mm",
    "HeavyExplosive": "Heavy Explosive Powder",
    "HeavyTruckC": "AU-A150 Taurine Rigger",
    "HeavyTruckW": "Cnute Cliffwrest",
    "ISGTC": "Daucus isg.III",
    "InfantryMine": "Crow's Foot Mine",
    "Iron": "Iron",
    "IronA": "Iron Alloy",
    "LRArtilleryAmmo": "300mm",
    "LandingCraftC": "AB-8 Acheron",
    "LandingCraftOffensiveC": "AB-11 Doru",
    "LandingCraftW": "Mulloy LPC",
    "LandingShipC": "Interceptor PA-12",
    "LandingShipW": "MacConmara Shorerunner",
    "LargeCrane": "BMS - Overseer Sky-Hauler",
    "LargeFieldATC": "945g Stygian Bolt",
    "LargeFieldCannonW": "Balfour Stockade 75mm",
    "LargeFieldLightArtilleryC": "120-68 Koronides Field Gun",
    "LargeFieldMortarC": "35-250 Alekto Heavy Cannon",
    "LargeFieldMultiW": "Rycker 4/3-F Wasp Nest",
    "LargeShipBaseShip": "BMS - Longhook",
    "LargeShipBattleshipC": "Titan",
    "LargeShipBattleshipW": "Callahan",
    "LargeShipDestroyerC": "Conqueror",
    "LargeShipDestroyerW": "Blacksteele",
    "LargeShipResourceShip": "BMS - Bowhead",
    "LargeShipStorageShip": "BMS - Bluefin",
    "LargeShipSubmarineC": "AC-b Trident",
    "LargeShipSubmarineW": "Nakki",
    "LightArtilleryAmmo": "120mm",
    "LightTank2InfantryC": "HC-2 Scorpion",
    "LightTankAmmo": "40mm",
    "LightTankArtilleryW": "Devitt-Caine Mk. IV MMR",
    "LightTankC": "H-5 Hatchet",
    "LightTankDefensiveW": "Devitt Ironhide Mk. IV",
    "LightTankFlameC": "H-19 Vulcan",
    "LightTankMobilityC": "H-8 Kranesca",
    "LightTankOffensiveC": "H-10 Pelekys",
    "LightTankW": "Devitt Mk. III",
    "LiquidContainer": "Liquid Container",
    "ListeningKit": "Listening Kit",
    "MGAmmo": "12.7mm",
    "MGC": "KRN886-127 Gast Machine Gun",
    "MGTC": "Lamentum mm.IV",
    "MGTW": "Malone Ratcatcher MK.1",
    "MGW": "Malone MK.2",
    "MaceW": "Falias Raiding Club",
    "MaintenanceSupplies": "Maintenance Supplies",
    "MaterialPlatform": "Material Pallet",
    "Mech": "Centurion MV-2",
    "MechW": "Herne QMW 1a Scourge Hunter",
    "MedicUniformC": "Medic Fatigues",
    "MedicUniformW": "Physician's Jacket",
    "MediumTank2C": "86K-a Bardiche",
    "MediumTank2IndirectW": "Gallagher Thornfall Mk. VI",
    "MediumTank2MultiW": "Gallagher Highwayman Mk. III",
    "MediumTank2RangeW": "Gallagher Outlaw Mk. II",
    "MediumTank2TwinC": "86K-c Ranseur",
    "MediumTank2W": "Gallagher Brigand Mk. I",
    "MediumTank3C": "90T-v Nemesis",
    "MediumTankATW": "Silverhand Lordscar - Mk. X",
    "MediumTankC": "85K-b Falchion",
    "MediumTankLargeC": "85V-g Talos",
    "MediumTankOffensiveC": "85K-a Spatha",
    "MediumTankSiegeW": "Silverhand Chieftain - Mk. VI",
    "MediumTankW": "Silverhand - Mk. IV",
    "Metal": "Salvage",
    "MetalBeamMaterials": "Metal Beam",
    "MiniTankAmmo": "30mm",
    "Mortar": "Cremari Mortar",
    "MortarAmmo": "Mortar Shell",
    "MortarAmmoFL": "Flare Mortar Shell",
    "MortarAmmoFlame": "Incendiary Mortar Shell",
    "MortarAmmoSH": "Shrapnel Mortar Shell",
    "MortarTankAmmo": "250mm Purity Shell",
    "MortarTankAmmoBR": "250mm Fury Shell",
    "MortarTankC": "HC-7 Ballista",
    "Motorboat": "BMS - Grouper",
    "MotorcycleC": "03MM Caster",
    "MotorcycleOffensiveC": "00MS Stinger",
    "MotorcycleW": "Kivela Power Wheel 80-1",
    "NavalUniformC": "Remex Garb",
    "NavalUniformW": "Gentleman's Peacoat",
    "OfficerUniformC": "Officialis' Attire",
    "OfficerUniformW": "Officer's Regalia",
    "Oil": "Oil",
    "Petrol": "Petrol",
    "PipeMaterials": "Pipe",
    "PistolAmmo": "8mm",
    "PistolC": "Ferro 879",
    "PistolLightW": "Cascadier 873",
    "PistolW": "Ahti Model 2",
    "RPGTW": "Cutler Foebreaker",
    "Radio": "Radio",
    "RadioBackpack": "Radio Backpack",
    "RainUniformC": "Legionary's Oilcoat",
    "RareMetal": "Rare Metal",
    "RelicAPC": "Heavy Infantry Carrier",
    "RelicArmouredCar": "Armoured Fighting Tractor",
    "RelicLightTank": "Storm Tank",
    "RelicMaterials": "Relic Materials",
    "RelicMediumTank": "PL-1 Phalanx",
    "RelicScoutVehicle": "Staff Car",
    "RelicTruck": "Repurposed Truck",
    "ReservePower": "Reserve Power",
    "ResourceContainer": "Resource Container",
    "Revolver": "Cometa T2-9",
    "RevolverAmmo": ".44",
    "RifleAmmo": "7.62mm",
    "RifleAutomaticC": "Catena rt.IV Auto-Rifle",
    "RifleAutomaticW": "Sampo Auto-Rifle 77",
    "RifleC": "Argenti r.II Rifle",
    "RifleHeavyC": "Volta r.I Repeater",
    "RifleHeavyW": "The Hangman 757",
    "RifleLightC": "Fuscina pi.I",
    "RifleLightW": "Blakerow 871",
    "RifleLongC": "KRR2-790 Omen",
    "RifleLongW": "Clancy Cinder M3",
    "RifleShortW": "No.2B Hawthorne",
    "RifleW": "No.2 Loughcaster",
    "RocketPartBottom": "A0E-9 Rocket Booster",
    "RocketPartCenter": "A0E-9 Rocket Body",
    "RocketPartTop": "A0E-9 Rocket Warhead",
    "RpgAmmo": "RPG",
    "RpgW": "Cutler Launcher 4",
    "SMGAmmo": "9mm",
    "SMGC": "The Pitch Gun mc.V",
    "SMGHeavyC": "Lionclaw mc.VIII",
    "SMGHeavyW": "No.1 The Liar Submachinegun",
    "SMGW": "Fiddler Submachine Gun Model 868",
    "SandbagMaterials": "Sandbag",
    "SatchelChargeT": "Havoc Charge Detonator",
    "SatchelChargeW": "Alligator Charge",
    "ScoutTankMultiW": "King Jester Mk. I-1",
    "ScoutTankOffensiveW": "King Gallant Mk. II",
    "ScoutTankW": "King Spire Mk. I",
    "ScoutUniformC": "Recon Camo",
    "ScoutUniformW": "Outrider's Mantle",
    "ScoutVehicleMobilityC": "UV-05a Argonaut",
    "ScoutVehicleOffensiveC": "UV-24 Icarus",
    "ScoutVehicleOffensiveW": "Drummond Spitfire 100d",
    "ScoutVehicleUtilityC": "UV-5c Odyssey",
    "ScoutVehicleUtilityW": "Drummond Loscann 55c",
    "ScoutVehicleW": "Drummond 100a",
    "ShipPart1": "Naval Hull Segments",
    "ShipPart2": "Naval Shell Plating",
    "ShipPart3": "Naval Turbine Components",
    "ShippingContainer": "Shipping Container",
    "ShotgunAmmo": "Buckshot",
    "ShotgunC": "KRF1-750 Dragonfly",
    "ShotgunW": "No.4 The Pillory Scattergun",
    "Shovel": "Shovel",
    "SledgeHammer": "Sledge Hammer",
    "SmallTrainEngine": "BMS Mineseeker",
    "SmallTrainLiquid": "BMS Tinderbox",
    "SmallTrainMaterial": "BMS Linerunner",
    "SmallTrainResource": "BMS Railtruck",
    "SmallTrainShipping": "BMS Stowheel",
    "SmokeGrenade": "PT-815 Smoke Grenade",
    "SniperRifleC": "KRR3-792 Auger",
    "SniperRifleW": "Clancy-Raca M4",
    "SnowUniformC": "Heavy Topcoat",
    "SnowUniformW": "Caoivish Parka",
    "SoldierSupplies": "Soldier Supplies",
    "SoldierUniformC": "Legionary Fatigues",
    "SoldierUniformW": "Infantry Battledress",
    "StickyBomb": "Anti-Tank Sticky Bomb",
    "Sulfur": "Sulfur",
    "SuperTankC": "O-75b Ares",
    "SuperTankW": "Cullen Predator Mk. III",
    "SwordC": "Eleos Infantry Dagger",
    "TankMine": "Abisme AT-99 Mine",
    "TankUniformC": "Tankman's Coveralls",
    "TankUniformW": "Padded Boiler Suit",
    "TanketteC": "T12 Actaeon Tankette",
    "TanketteFlameC": "T14 Vesta Tankette",
    "TanketteMultiC": "T13 Deioneus Rocket Battery",
    "TanketteOffensiveC": "T20 Ixion Tankette",
    "TorpedoAmmo": "Moray Torpedo",
    "TrailerLiquid": "Rooster - Lamploader",
    "TrailerMaterial": "Rooster - Tumblebox",
    "TrailerResource": "Rooster - Junkwagon",
    "TrainCaboose": "BMS Roadhouse",
    "TrainCoal": "BMS Rockhold",
    "TrainCombatCarC": "Aegis Steelbreaker K5a",
    "TrainCombatCarW": "O'Brien Warsmith v.215",
    "TrainEngine": "BMS Black Bolt",
    "TrainFlatbed": "BMS Longrider",
    "TrainHospital": "BMS Bloodtender",
    "TrainInfantry": "BMS Holdout",
    "TrainLRArtillery": "Tempest Cannon RA-2",
    "TraumaKit": "Trauma Kit",
    "Tripod": "Tripod",
    "TruckC": "R-1 Hauler",
    "TruckDefensiveW": "Dunne Leatherback 2a",
    "TruckLiquidC": "RR-3 Stolon Tanker",
    "TruckLiquidW": "Dunne Fuelrunner 2d",
    "TruckMobilityC": "R-5b Sisyphus Hauler",
    "TruckMobilityW": "Dunne Landrunner 12c",
    "TruckMultiC": "R-17 Retiarius Skirmisher",
    "TruckOffensiveC": "R-9 Speartip Escort",
    "TruckResourceC": "R-5 Atlas Hauler",
    "TruckResourceW": "Dunne Loadlugger 3c",
    "TruckW": "Dunne Transport",
    "UnexplodedOrdnance": "Unexploded Ordnance",
    "Water": "Water",
    "WaterBucket": "Water Bucket",
    "WaterMine": "E680-S Rudder Lock",
    "WindsockT": "Wind Sock",
    "Wood": "Refined Materials",
    "WorkHammer": "Hammer",
    "WorkWrench": "Wrench",
    "Wreckage": "Wreckage",
}


def get_item_display_name(code: str) -> str:
    """Get the display name for an item code."""
    return ITEM_DISPLAY_NAMES.get(code, code)


# Item tags - maps abbreviations/slang to item codes
ITEM_TAGS: dict[str, list[str]] = {
    # Tanks
    "lt": [
        "LightTankC", "LightTankW", "LightTankMobilityC", "LightTankDefensiveW",
        "LightTankFlameC", "LightTankOffensiveC", "LightTank2InfantryC", "LightTankArtilleryW"
    ],
    "bt": [
        "BattleTankC", "BattleTankW", "BattleTankDefensiveW", "BattleTankATC",
        "BattleTankHeavyArtilleryC", "BattleTankHeavyArtilleryW"
    ],
    "mpt": ["MediumTankC"],
    "falchion": ["MediumTankC"],
    "sh": ["MediumTankW", "MediumTankATW", "MediumTankSiegeW"],
    "silverhand": ["MediumTankW", "MediumTankATW", "MediumTankSiegeW"],
    "supertank": ["SuperTankC", "SuperTankW"],

    # Resources
    "bmat": ["Cloth"],
    "bmats": ["Cloth"],
    "rmat": ["Wood"],
    "rmats": ["Wood"],
    "cmat": ["FacilityMaterials1"],
    "cmats": ["FacilityMaterials1"],
    "comp": ["Components"],
    "comps": ["Components"],
    "conc": ["Concrete"],
    "ms": ["MaintenanceSupplies"],
    "ss": ["SoldierSupplies"],
    "shirt": ["SoldierSupplies"],
    "shirts": ["SoldierSupplies"],

    # Weapons
    "at": [
        "ATRifleW", "ATRifleLightC", "ATRPGC", "ATRPGHeavyC",
        "ATRPGHeavyW", "ATRPGW", "ATRPGLightC"
    ],
    "atr": [
        "ATRifleW", "ATRifleLightC", "ATRifleTC", "ATRifleSniperC",
        "ATRifleAssaultW", "ATRifleAutomaticW"
    ],
    "rpg": ["ATRPGC", "ATRPGHeavyC", "ATRPGHeavyW", "ATRPGW", "ATRPGLightC", "RpgW"],
    "cutler": ["RpgW", "RPGTW"],
    "bonesaw": ["ATRPGW", "ATRPGTW"],
    "ignifist": ["ATRPGLightC"],
    "mg": ["MGC", "MGW", "MGTC", "MGTW", "FieldMGC", "FieldMGW"],
    "hmg": ["MGTC", "MGTW", "FieldMGC", "FieldMGW"],
    "smg": ["SMGC", "SMGW", "SMGHeavyC", "SMGHeavyW"],
    "ar": ["AssaultRifleC", "AssaultRifleW", "AssaultRifleHeavyC", "AssaultRifleHeavyW"],
    "rifle": [
        "RifleC", "RifleW", "RifleLightC", "RifleLightW",
        "RifleHeavyC", "RifleHeavyW"
    ],
    "sniper": ["SniperRifleC", "SniperRifleW", "RifleLongC", "RifleLongW"],

    # Grenades
    "mammon": ["HEGrenade"],
    "he": ["HEGrenade"],
    "frag": ["GrenadeC", "GrenadeW"],
    "smoke": ["SmokeGrenade"],
    "gas": ["GreenAsh"],

    # Logistics
    "logi": ["TruckC", "TruckW", "TruckMobilityC", "TruckMobilityW", "FlatbedTruck", "Crane"],
    "truck": [
        "TruckC", "TruckW", "TruckMobilityC", "TruckMobilityW",
        "TruckResourceC", "TruckResourceW"
    ],
    "flatbed": ["FlatbedTruck"],
    "crane": ["Crane", "LargeCrane"],

    # Artillery
    "arty": ["FieldMortarC", "FieldMortarW", "EmplacedHeavyArtilleryC", "EmplacedHeavyArtilleryW"],
    "mortar": ["Mortar", "MortarTankC", "FieldMortarC", "FieldMortarW"],
    "isg": ["ISGTC"],

    # Ammo
    "762": ["RifleAmmo"],
    "792": ["AssaultRifleAmmo"],
    "9mm": ["SMGAmmo"],
    "127": ["MGAmmo"],
    "12.7": ["MGAmmo"],
    "40mm": ["LightTankAmmo"],
    "68mm": ["ATAmmo"],
    "75mm": ["BattleTankAmmo"],
}


def get_item_codes_by_tag(tag: str) -> list[str]:
    """Get item codes that match a slang/abbreviation tag."""
    return ITEM_TAGS.get(tag.lower(), [])


# Vehicle item codes for filtering
VEHICLE_PREFIXES = [
    "LightTank", "BattleTank", "MediumTank", "SuperTank", "DestroyerTank", "ScoutTank",
    "ArmoredCar", "HalfTrack", "Tankette", "Truck", "Bus", "Ambulance",
    "ScoutVehicle", "Motorcycle", "Harvester", "Crane", "FlatbedTruck",
    "Construction", "Mech", "Barge", "Motorboat", "Gunboat", "Freighter",
    "LandingCraft", "LandingShip", "LargeShip", "Train", "SmallTrain",
    "Bicycle", "HeavyTruck", "Trailer",
]


def is_vehicle(item_code: str) -> bool:
    """Check if an item code represents a vehicle."""
    return any(item_code.startswith(prefix) for prefix in VEHICLE_PREFIXES)


def get_vehicle_item_codes() -> list[str]:
    """Get all item codes that are vehicles."""
    return [code for code in ITEM_DISPLAY_NAMES if is_vehicle(code)]
